### ISSUE TITLE
Bundle has a lot of unused configurations.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/OXIDConnectorBundle#18]
Seems like most of things defined here are not used anywhere

``` yaml
ongr_oxid:
    database_mapping:
        oxid:
            tags:
                @shop_tag: '_1'
                @lang_tag: '_1_en'
            shop_id: 0
            lang_id: 0
    entity_namespace: ONGROXIDConnectorBundle
```
